name = "mock-rpc"
main = "src/index.ts"
compatibility_date = "2023-01-21"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
    { binding = "STORAGE", id = "" }
]

route = "zkevm.kindynos.mx"

[env.dev]
kv_namespaces = [
    { binding = "STORAGE", id = "" }
]

vars = { TESTNET = true }
route = "zkevm-testnet.kindynos.mx"
